# docker-compose.prod.yml (Production)
version: '3.8'

services:
  bellapp:
    build: ./bellapp
    ports:
      - "5000:5000"
    restart: always
    container_name: bellapp
    volumes:
      - ./bellapp/logs:/bellapp/logs
    depends_on:
      - config_service
    environment:
      # Production mode with auto-detection
      AUTO_DETECT_CONFIG_SERVICE: "true"
      CONFIG_SERVICE_PORT: "5002"
      ENVIRONMENT: "production"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  newsapp:
    build: ./newsapp
    environment:
      - VITE_API_BASE_URL=http://bellapp:5000
      - HOST_IP=${HOST_IP:-auto}
    ports:
      - "8000:8000"
      - "5173:5173"
    restart: always
    container_name: newsapp
    depends_on:
      - bellapp

  config_service:
    build:
      context: .
      dockerfile: Dockerfile_config
    network_mode: "host"
    restart: always
    container_name: config_service
    volumes:
      - /etc/netplan:/etc/netplan
      - ./config_service_logs:/var/log
    privileged: true
    environment:
      IN_DOCKER_TEST_MODE: "false"   