# docker-compose.yml (Development)
version: '3.8'

services:
  # Main Python Flask web application (bellapp)
  bellapp:
    build: ./bellapp
    ports:
      - "5000:5000"
    restart: always
    container_name: bellapp
    volumes:
      - ./bellapp/logs:/bellapp/logs
    depends_on:
      - config_service
    environment:
      # Remove hardcoded IP - let the app auto-detect
      # The Python app will dynamically detect the host IP
      AUTO_DETECT_CONFIG_SERVICE: "true"
      CONFIG_SERVICE_PORT: "5002"
    extra_hosts:
      # This allows the container to reach the host
      - "host.docker.internal:host-gateway"

  # Laravel news application  
  newsapp:
    build: ./newsapp
    environment:
      - VITE_API_BASE_URL=http://bellapp:5000
    ports:
      - "8000:8000"
      - "5173:5173"
    restart: always
    container_name: newsapp
    depends_on:
      - bellapp

  # Ubuntu Configuration Service
  config_service:
    build:
      context: .
      dockerfile: Dockerfile_config
    network_mode: "host"
    restart: always
    container_name: config_service
    volumes:
      - /etc/netplan:/etc/netplan
      - ./config_service_logs:/var/log
    privileged: true